apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: Red Hat Advanced Cluster Security Operator
    kubernetes.io/metadata.name: rhacs-operator
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/sync-wave: "0"
  name: rhacs-operator