{{- if (ne .Values.operator.approvalPlan "Automatic") -}}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: acs-operator-installplan-approver
  namespace: rhacs-operator
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
          env:
            - name: OP_APPROVAL_PLAN
              value: {{ .Values.operator.approvalPlan }} 
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash
              if [ "$OP_APPROVAL_PLAN" == "Automatic" ];then
                 echo "INFO: Install Plan strategy $OP_APPROVAL_PLAN does not require no more action."
                 exit 0
              else
                # Wait for InstallPlan to be created.
                attempt_counter=0
                max_attempts=20
                INSTALL_PLAN=''
                echo "INFO: Waiting for InstallPlan to be available..."
                while true;do
                  INSTALL_PLAN=$(oc get installplan -n rhacs-operator --no-headers | awk '{print $1}' 2>/dev/null)
                  if [ -n "$INSTALL_PLAN" ];then
                      echo "INFO: InstallPlan $INSTALL_PLAN of ACS operator now exist... "
                      break;
                  fi

                  echo "Waiting for ACS InstallPlan to be generated ..."
                  sleep 5
                done

                # Update the installPlan
                oc patch installplan $INSTALL_PLAN -n rhacs-operator --type merge --patch '{"spec":{"approved":true}}'
                if [ $? -eq 0 ]; then
                    echo "INFO: Update installPlan of ACS Operator succeed"
                else
                    echo "Error: Failed to update the InstallPlan of the ACS Operator"
                    exit 1
                fi
              fi
          imagePullPolicy: Always
          name: approve-acs-operator-installplan
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: acs-operator-installer
      serviceAccountName: acs-operator-installer
      terminationGracePeriodSeconds: 30
{{- end -}}