apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: acs-operator-installer
  namespace: rhacs-operator
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - installplans
    verbs:
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: acs-operator-installer
  namespace: rhacs-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: acs-operator-installer
subjects:
  - kind: ServiceAccount
    name: acs-operator-installer
    namespace: rhacs-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: acs-operator-installer
  namespace: rhacs-operator
