apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
check: |
  health_status = {}
  if obj.status ~= nil then
    if obj.status.currentCSV ~= nil then
        health_status.status = 'Healthy'
        health_status.message = 'Install Successful'
        return health_status
    end

    health_status.status = "Progressing"
    health_status.message = "Waiting for Central to deploy."
    return health_status
  end
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  name: rhacs-operator
  namespace: rhacs-operator
spec:
  channel: stable
  installPlanApproval: {{ .Values.operator.approvalPlan }}
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.operator.version }}