kind: Secret
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: central-admin
  namespace: stackrox
data:
  password: UzdBV0NUODNRcGJ0TVA2RzVFckxtekR4Ywo=
type: Opaque
