# ApprovalPlan values : Manual or Automatic
operator:
  approvalPlan: Automatic
  version: rhacs-operator.v4.5.4

components:
  central:
    enabled: true
  securedcluster:
    enabled: true

acs-secured-cluster:
  cluster:
    clusterName: aro-mgmtlab
  central:
    # put this value without https
    endpoint: 'central-stackrox.apps.cluster-gcrdc.gcrdc.sandbox1276.opentlc.com'