# ApprovalPlan values : Manual or Automatic
operator:
  approvalPlan: Automatic
  version: rhacs-operator.v4.5.4

components:
  central:
    enabled: true
  securedcluster:
    enabled: true

acs-secured-cluster:
  cluster:
    clusterName: aro-mgmtlab
  central:
    # put this value with https
    endpoint: 'central-stackrox.apps.cluster-6gpg5.6gpg5.sandbox2279.opentlc.com'