apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: create-cluster-init-bundle
  namespace: stackrox
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
          env:
            - name: ROX_CENTRAL_ENDPOINT
              value: {{ .Values.central.endpoint }} 
            - name: ROX_API_TOKEN
              value:  {{ .Values.central.token }}
            - name: ROX_BUNDLE_NAME
              value:  {{ .Values.clusterName }}
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash
              # Wait for central to be ready
              attempt_counter=0
              max_attempts=20
              echo "Waiting for central to be available..."
              until $(curl -k --output /dev/null --silent --head --fail https://$ROX_CENTRAL_ENDPOINT:443); do
                  if [ ${attempt_counter} -eq ${max_attempts} ];then
                    echo "Max attempts reached"
                    exit 1
                  fi

                  printf '.'
                  attempt_counter=$(($attempt_counter+1))
                  echo "Made attempt $attempt_counter, waiting..."
                  sleep 5
              done
              echo "INFO: The central is available ..."

              curl -s -v -k -L -H "Authorization: Bearer $ROX_API_TOKEN" https://$ROX_CENTRAL_ENDPOINT:443/api/cli/download/roxctl-linux -o /tmp/roxctl
              if [ $? -eq 0 ]; then
                  echo "INFO: Retrieve of roxctl command succeed"
              else
                  echo "Error: Retrieve of roxctl command failed"
                  exit 1
              fi

              chmod +x /tmp/roxctl
              if [ $? -eq 0 ]; then
                  echo "INFO: Change roxctl command rigths succeed"
              else
                  echo "Error: Change roxctl command rigths failed"
                  exit 1
              fi
              
              /tmp/roxctl --insecure-skip-tls-verify central init-bundles generate $ROX_BUNDLE_NAME  --endpoint $ROX_CENTRAL_ENDPOINT:443  --output-secrets /tmp/"$ROX_BUNDLE_NAME".yaml
              if [ $? -eq 0 ]; then
                  echo "INFO: Retrieve init bundles succeed"
              else
                  echo "Error: Retrieve init bundles failed"
                  exit 1
              fi

              if oc get secret/sensor-tls &> /dev/null; then
                echo "Error: cluster-init bundle has already been configured, doing nothing"
                exit 0
              else

                # Display init bundle generated
                cat /tmp/"$ROX_BUNDLE_NAME".yaml

                echo "INFO: Applying init bundle generated "
                # No jq in container, python to the rescue
                oc apply -f /tmp/"$ROX_BUNDLE_NAME".yaml

                # Touch SecuredCluster to force operator to reconcile
                oc label SecuredCluster stackrox-secured-cluster-services cluster-init-job-status=created

                echo "INFO: ACS Cluster init bundle generated and applied"
              fi
          imagePullPolicy: Always
          name: create-cluster-init-bundle
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: rhacs-services
      serviceAccountName: rhacs-services
      terminationGracePeriodSeconds: 30
