
{{ $route := ternary (lookup "config.openshift.io/v1" "Ingress" "" "cluster") "" true }}
{{ if $route }}
  {{ $route =printf "%s%s"  "central-stackrox." $route.spec.domain }}
{{ else }}
  {{ $route = "" }}
{{ end }}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/metadata.name: rhacs-central
    argocd.argoproj.io/sync-wave: "1"
  name: declarative-configurations
  namespace: stackrox
data:
  openshift-auth.yaml: |
    name: Openshift-Auth
    uiEndpoint: {{ $route }} 
    groups:
    {{ .Values.oauth_provider.groups | toYaml | indent 4 | trim }}
    openshift:
        enable: true