apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/metadata.name: rhacs-central
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: declarative-configurations
  namespace: stackrox
data:
  openshift-auth.yaml: |
    name: Openshift-Auth
    uiEndpoint: central-stackrox.{{ (lookup "config.openshift.io/v1" "Ingress" "" "cluster").spec.domain }} 
    groups:
    {{ .Values.oauth_provider.groups | toYaml | indent 4 | trim }}
    openshift:
        enable: true